version: '3.8'

services:
  postgres:
    image: dorothag/database:latest  
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: "postgres" 
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment: 
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    expose:
      - "5672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

  session-service:
    image: dorothag/session-service:latest  
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: users_db
      JAVA_OPTS: "-Xms64m -Xmx256m"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

  hotel-service:
    image: dorothag/hotel-service:latest  
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: hotels_db
      JAVA_OPTS: "-Xms64m -Xmx256m"
    expose:
      - "8082"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
      placement:
        constraints: [node.role == worker]

  payment-service:
    image: dorothag/payment-service:latest  
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: payments_db
      JAVA_OPTS: "-Xms128m -Xmx512m"
    expose:
      - "8084"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
      placement:
        constraints: [node.role == worker]

  loyalty-service:
    image: dorothag/loyalty-service:latest  
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: balances_db
      JAVA_OPTS: "-Xms64m -Xmx256m"
    expose:
      - "8085"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
      placement:
        constraints: [node.role == worker]

  report-service:
    image: dorothag/report-service:latest  
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: statistics_db
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
      JAVA_OPTS: "-Xms64m -Xmx256m"
    expose:
      - "8086"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
      placement:
        constraints: [node.role == worker]      

  booking-service:
    image: dorothag/booking-service:latest  
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: reservations_db
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
      HOTEL_SERVICE_HOST: hotel-service
      HOTEL_SERVICE_PORT: 8082
      PAYMENT_SERVICE_HOST: payment-service
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty-service
      LOYALTY_SERVICE_PORT: 8085
      JAVA_OPTS: "-Xms64m -Xmx256m"
    expose:
      - "8083"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 5
      placement:
        constraints: [node.role == worker]


  gateway-service:
    image: dorothag/gateway-service:latest  
    environment: 
      SESSION_SERVICE_HOST: session-service
      SESSION_SERVICE_PORT: 8081
      HOTEL_SERVICE_HOST: hotel-service
      HOTEL_SERVICE_PORT: 8082
      BOOKING_SERVICE_HOST: booking-service
      BOOKING_SERVICE_PORT: 8083
      PAYMENT_SERVICE_HOST: payment-service
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty-service
      LOYALTY_SERVICE_PORT: 8085
      REPORT_SERVICE_HOST: report-service
      REPORT_SERVICE_PORT: 8086
      JAVA_OPTS: "-Xms128m -Xmx512m"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 25s
        max_attempts: 5

networks:
  default:
    driver: overlay